# this workflow should be assigned to dedicated runner when available
name: Ledger Benchmark

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE : full
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  benchmark:
    runs-on: ubuntu-latest-8-core-x64
    steps:
      - name: Install required libs
        run: |
          sudo apt-get update
          sudo apt-get install libssl-dev

      - name: Setup api.github.com credentials
        uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68
        with:
          machine: api.github.com
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PASSWORD }}

      - name: Setup github.com credentials
        uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68
        with:
          machine: github.com
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PASSWORD }}

      - name: Configure git rewrite
        run: |
          mkdir -p $HOME/.config/git
          echo '[url "https://github.com/"]' >> $HOME/.config/git/config
          echo '  insteadOf = "git@github.com:"' >> $HOME/.config/git/config
          echo '  insteadOf = "git@github.com/"' >> $HOME/.config/git/config
          echo '  insteadOf = "ssh://git@github.com/"' >> $HOME/.config/git/config

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  #v5.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@51f3067b56fe8ae331890c77d4e454f6d60615ff
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            netrc-file = ${{ env.HOME }}/.netrc
            access-tokens = github.com=${{ secrets.GH_PASSWORD }} api.github.com=${{ secrets.GH_PASSWORD }}
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            extra-substituters = https://cache.iog.io file://${{ runner.temp }}/nix-binary-cache
            accept-flake-config = true

      - name: Cache Nix
        uses: input-output-hk/actions/attic@dbb6ea6d50ffc37a2d481fd8047aff028bac3223 # latest
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          endpoint: https://attic.ci.iog.io
          cache: midnight-public
          access_token: ${{ secrets.ATTIC_CACHE_TOKEN }}

      - name: Configure cargo
        run: .github/scripts/configure-cargo.sh

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4

      - name: Benchmark compare
        run: |
          git remote update
          git fetch
          git checkout master
          nix develop .#default -c cargo bench --all-features --bench benchmarking -- --save-baseline before
          rm target/release -rf
          git stash
          git checkout $BRANCH_NAME
          nix develop .#default -c cargo bench --all-features --bench benchmarking -- --save-baseline after
          nix develop .#default -c cargo bench --all-features --bench benchmarking -- --load-baseline before --baseline after | tee benchmark-output.txt
          rm target/release -rf

      - name: Benchmark with criterion
        run: |
          nix develop .#default -c cargo install cargo-criterion
          nix develop .#default -c cargo criterion --all-features

      - name: Attach benchmark output
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: benchmark-report-output
          path: benchmark-output.txt

      - name: Attach HTML benchmark report
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: benchmark-report
          path: target/criterion/reports/
