name: Ledger Build and Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'ledger-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git rewrite
        run: |
          mkdir -p $HOME/.config/git
          echo '[url "https://github.com/"]' >> $HOME/.config/git/config
          echo '  insteadOf = "git@github.com:"' >> $HOME/.config/git/config
          echo '  insteadOf = "git@github.com/"' >> $HOME/.config/git/config
          echo '  insteadOf = "ssh://git@github.com/"' >> $HOME/.config/git/config

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@51f3067b56fe8ae331890c77d4e454f6d60615ff # v31.10.2
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            extra-substituters = https://cache.iog.io file://${{ runner.temp }}/nix-binary-cache
            accept-flake-config = true

      - name: Cache Nix
        uses: input-output-hk/actions/attic@6d5d62ad59441a3c869a0e8abee4e1bf8b440c2f
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          endpoint: https://attic.ci.iog.io
          cache: midnight-public
          access_token: ${{ secrets.ATTIC_CACHE_TOKEN }}

      - name: Configure cargo
        run: .github/scripts/configure-cargo.sh

      - name: Cache dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4

      - name: Fix Nix permissions (needed on macos self hosted runner)
        run: |
          sudo mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
          sudo chown -R $USER:nixbld /nix/var/nix/{profiles,gcroots}/per-user/$USER
        shell: bash # Ensure bash is used for these commands

      - name: Add Homebrew and git bin to PATH for Yarn, verify git is installed
        run: |
          echo "/opt/homebrew/bin" >> $GITHUB_PATH
          echo "/usr/bin" >> $GITHUB_PATH
          which git
          git --version

      - name: Spellcheck comments
        run: |
          nix develop .#ci -c cargo spellcheck -j1

      # Run Cargo Clippy on the whole workspace with all features. This is important
      # to avoid bitrot of code that is feature gated behind non-default features
      # or in pkgs which aren't in Cargo.toml#default-members, since we don't
      # include --workspace or --all-features in ouor build-and-test recipe
      # below.
      # We still permit certain Clippy rules with `-A` args. since they will be
      # addressed in upcoming PRs and changes that are currently in progress. This
      # allows us to start running these checks even before they are fully implemented.
      - name: Cargo clippy (--all-targets --workspace --all-features --all -- -Dwarnings -Aclippy::type_complexity -Aclippy::mutable_key_type -Aclippy::too_many_arguments -Aclippy::derived_hash_with_manual_eq -Aclippy::unbuffered_bytes)
        run: MIDNIGHT_LEDGER_EXPERIMENTAL=1 MIDNIGHT_PP='' cargo clippy --all-targets --workspace --all-features --all -- -Dwarnings -Aclippy::type_complexity -Aclippy::mutable_key_type -Aclippy::too_many_arguments -Aclippy::derived_hash_with_manual_eq -Aclippy::unbuffered_bytes

      - name: Cargo doc
        run: MIDNIGHT_LEDGER_EXPERIMENTAL=1 MIDNIGHT_PP='' cargo doc --all-features --no-deps

      - name: Cargo audit
        run: MIDNIGHT_LEDGER_EXPERIMENTAL=1 nix develop .#ci -c cargo audit

  build-wasm:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git rewrite
        run: |
          mkdir -p $HOME/.config/git
          echo '[url "https://github.com/"]' >> $HOME/.config/git/config
          echo '  insteadOf = "git@github.com:"' >> $HOME/.config/git/config
          echo '  insteadOf = "git@github.com/"' >> $HOME/.config/git/config
          echo '  insteadOf = "ssh://git@github.com/"' >> $HOME/.config/git/config

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

      - name: Install Nix (2)
        uses: cachix/install-nix-action@51f3067b56fe8ae331890c77d4e454f6d60615ff # v31.10.2
        with:
          nix_path: nixpkgs=channel:nixos-unstable #trya
          extra_nix_config: |
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            extra-substituters = https://cache.iog.io file://${{ runner.temp }}/nix-binary-cache
            accept-flake-config = true

      - name: Cache Nix
        uses: input-output-hk/actions/attic@6d5d62ad59441a3c869a0e8abee4e1bf8b440c2f
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          endpoint: https://attic.ci.iog.io
          cache: midnight-public
          access_token: ${{ secrets.ATTIC_CACHE_TOKEN }}

      - name: Configure cargo
        run: .github/scripts/configure-cargo.sh

      - name: Cache dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4

      - name: Fix Nix permissions (needed on macos self hosted runner)
        run: |
          sudo mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
          sudo chown -R $USER:nixbld /nix/var/nix/{profiles,gcroots}/per-user/$USER
        shell: bash # Ensure bash is used for these commands

      - name: Build ledger-wasm
        run: nix build .#ledger-wasm

      - name: Build onchain-runtime-wasm
        run: nix build .#onchain-runtime-wasm

      - name: Build zkir-wasm
        run: nix build .#zkir-wasm

  integration-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git rewrite
        run: |
          mkdir -p $HOME/.config/git
          echo '[url "https://github.com/"]' >> $HOME/.config/git/config
          echo '  insteadOf = "git@github.com:"' >> $HOME/.config/git/config
          echo '  insteadOf = "git@github.com/"' >> $HOME/.config/git/config
          echo '  insteadOf = "ssh://git@github.com/"' >> $HOME/.config/git/config

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

      - name: Install Nix (2)
        uses: cachix/install-nix-action@51f3067b56fe8ae331890c77d4e454f6d60615ff # v31.10.2
        with:
          nix_path: nixpkgs=channel:nixos-unstable #trya
          extra_nix_config: |
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            extra-substituters = https://cache.iog.io file://${{ runner.temp }}/nix-binary-cache
            accept-flake-config = true

      - name: Cache Nix
        uses: input-output-hk/actions/attic@6d5d62ad59441a3c869a0e8abee4e1bf8b440c2f
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          endpoint: https://attic.ci.iog.io
          cache: midnight-public
          access_token: ${{ secrets.ATTIC_CACHE_TOKEN }}

      - name: Configure cargo
        run: .github/scripts/configure-cargo.sh

      - name: Cache dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4
      - name: Build 
        run: nix build .#integration-test-deps

      - name: Add git bin to PATH for Yarn, verify git is installed
        run: |
          echo "/usr/bin" >> $GITHUB_PATH
          which git
          git --version

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22

      - name: Run integration tests
        run: |
          export MN_AXIOS=true
          set -o pipefail
          cd integration-tests
          yarn
          yarn lint
          yarn build
          yarn test:coverage:prepare
          nix develop .#ci -c yarn test:coverage | tee ./coverage.txt

      - name: Upload Logs
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: logs-${{ matrix.os }}
          path: integration-tests/logs/

      - name: Upload Test Results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: always()
        with:
          name: "ledger-wasm-test-results-ctrf-${{ matrix.os }}"
          path: "./integration-tests/reports/ctrf-report.json"

      - name: Upload Artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: "ledger-wasm-test-results-junit-${{ matrix.os }}"
          path: ./integration-tests/reports/test-report.xml

  build-ledger:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git rewrite
        run: |
          mkdir -p $HOME/.config/git
          echo '[url "https://github.com/"]' >> $HOME/.config/git/config
          echo '  insteadOf = "git@github.com:"' >> $HOME/.config/git/config
          echo '  insteadOf = "git@github.com/"' >> $HOME/.config/git/config
          echo '  insteadOf = "ssh://git@github.com/"' >> $HOME/.config/git/config

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

      - name: Install Nix (2)
        uses: cachix/install-nix-action@51f3067b56fe8ae331890c77d4e454f6d60615ff # v31.10.2
        with:
          nix_path: nixpkgs=channel:nixos-unstable #trya
          extra_nix_config: |
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            extra-substituters = https://cache.iog.io file://${{ runner.temp }}/nix-binary-cache
            accept-flake-config = true

      - name: Cache Nix
        uses: input-output-hk/actions/attic@6d5d62ad59441a3c869a0e8abee4e1bf8b440c2f
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          endpoint: https://attic.ci.iog.io
          cache: midnight-public
          access_token: ${{ secrets.ATTIC_CACHE_TOKEN }}

      - name: Configure cargo
        run: .github/scripts/configure-cargo.sh

      - name: Cache dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4

      - name: Fix Nix permissions (needed on macos self hosted runner)
        run: |
          sudo mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
          sudo chown -R $USER:nixbld /nix/var/nix/{profiles,gcroots}/per-user/$USER
        shell: bash # Ensure bash is used for these commands

      - name: Add Homebrew and git bin to PATH for Yarn, verify git is installed
        run: |
          echo "/opt/homebrew/bin" >> $GITHUB_PATH
          echo "/usr/bin" >> $GITHUB_PATH
          which git
          git --version

      - name: Build and Test (default features)
        run: |
          cargo install cargo2junit
          nix develop .#ci -c cargo test --release -- -Z unstable-options --format json --report-time --nocapture --test-threads=1 | tee test-results.json
          # Filter is a workaround for johnterickson/cargo2junit#85
          jq -cR 'fromjson? | select( .type != "report" )' test-results.json | cargo2junit > ./target/test-results.xml
          cp test-results.json ./target/

  build-proof-server:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git rewrite
        run: |
          mkdir -p $HOME/.config/git
          echo '[url "https://github.com/"]' >> $HOME/.config/git/config
          echo '  insteadOf = "git@github.com:"' >> $HOME/.config/git/config
          echo '  insteadOf = "git@github.com/"' >> $HOME/.config/git/config
          echo '  insteadOf = "ssh://git@github.com/"' >> $HOME/.config/git/config

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

      - name: Install Nix (2)
        uses: cachix/install-nix-action@51f3067b56fe8ae331890c77d4e454f6d60615ff # v31.10.2
        with:
          nix_path: nixpkgs=channel:nixos-unstable #trya
          extra_nix_config: |
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            extra-substituters = https://cache.iog.io file://${{ runner.temp }}/nix-binary-cache
            accept-flake-config = true

      - name: Cache Nix
        uses: input-output-hk/actions/attic@6d5d62ad59441a3c869a0e8abee4e1bf8b440c2f
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          endpoint: https://attic.ci.iog.io
          cache: midnight-public
          access_token: ${{ secrets.ATTIC_CACHE_TOKEN }}

      - name: Configure cargo
        run: .github/scripts/configure-cargo.sh

      - name: Cache dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4

      - name: Fix Nix permissions (needed on macos self hosted runner)
        run: |
          sudo mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
          sudo chown -R $USER:nixbld /nix/var/nix/{profiles,gcroots}/per-user/$USER
        shell: bash # Ensure bash is used for these commands

      - name: Add Homebrew and git bin to PATH for Yarn, verify git is installed
        run: |
          echo "/opt/homebrew/bin" >> $GITHUB_PATH
          echo "/usr/bin" >> $GITHUB_PATH
          which git
          git --version

      - name: Build and Test - Proof server (default features)
        run: |
          cargo install cargo2junit
          cd proof-server
          nix develop .#ci -c cargo test --release -- -Z unstable-options --format json --report-time --nocapture --test-threads=1 | tee test-results-proof-server.json
          # Filter is a workaround for johnterickson/cargo2junit#85
          jq -cR 'fromjson? | select( .type != "report" )' test-results-proof-server.json | cargo2junit > ../target/test-results-proof-server.xml
          cp test-results-proof-server.json ../target/

      - name: Upload Artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: "proof-server-test-results-${{ matrix.os }}"
          path: target/test-*
