name: Prepare cost model docker image

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      MIDNIGHTBOT_PACKAGES_WRITE:
        required: true
      ATTIC_CACHE_TOKEN:
        required: true
      GH_USERNAME:
        required: true
      GH_PASSWORD:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest-8-core-x64
    steps:
      - name: Setup api.github.com credentials
        uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68
        with:
          machine: api.github.com
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PASSWORD }}

      - name: Setup github.com credentials
        uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68
        with:
          machine: github.com
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PASSWORD }}

      - name: Docker login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ghcr.io
          username: ntwrk-bot
          password: ${{ secrets.MIDNIGHTBOT_PACKAGES_WRITE }}

      - name: Configure git rewrite
        run: |
          mkdir -p $HOME/.config/git
          echo '[url "https://github.com/"]' >> $HOME/.config/git/config
          echo '  insteadOf = "git@github.com:"' >> $HOME/.config/git/config
          echo '  insteadOf = "git@github.com/"' >> $HOME/.config/git/config
          echo '  insteadOf = "ssh://git@github.com/"' >> $HOME/.config/git/config

      - name: Checkout ledger repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Install Nix
        uses: cachix/install-nix-action@51f3067b56fe8ae331890c77d4e454f6d60615ff
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            netrc-file = ~/.netrc
            access-tokens = github.com=${{ secrets.GH_PASSWORD }} api.github.com=${{ secrets.GH_PASSWORD }}
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            extra-substituters = https://cache.iog.io file://${{ runner.temp }}/nix-binary-cache
            accept-flake-config = true

      - name: Cache Nix
        uses: input-output-hk/actions/attic@dbb6ea6d50ffc37a2d481fd8047aff028bac3223 # latest
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          endpoint: https://attic.ci.iog.io
          cache: midnight-public
          access_token: ${{ secrets.ATTIC_CACHE_TOKEN }}

      - name: Configure cargo
        run: .github/scripts/configure-cargo.sh

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: stable # Or 'nightly', 'beta', or a specific version like '1.70.0'
          override: true
          profile: minimal # Installs rustc, cargo, and rust-std. Use 'default' for rustfmt, clippy, etc.

      - name: Cache dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4

      - name: Create and push cost model docker image
        run: |
          nix develop . --command generate-cost-model/build-docker.sh
          docker push ghcr.io/midnight-ntwrk/generate-ledger-cost-model:latest

